# Configuration for actionlint
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Define custom self-hosted runner labels
self-hosted-runner:
  # Labels for self-hosted runners
  labels:
    - o4-k8s-runner-set-o4
